name    'ghoneycutt-common'
version '0.3.0'
source 'UNKNOWN'
author 'herffjones'
license 'Apache License, Version 2.0'
summary 'UNKNOWN'
description 'UNKNOWN'
project_page 'UNKNOWN'

dependency 'puppetlabs/stdlib', '>= 3.2.x'
